parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: 3306
    database_name: edusoho
    database_user: root
    database_password: '1qaz@WSX'
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: zh_CN
    secret: thkvch2y10gg40o4w00ck0oscok0g8o
    user_partner: none